### ISSUE TITLE
New dataset: dat.bakdash2021

### ISSUE THREAD

**Issue by jbakdash** [wviechtb/metadat#18]
Here's a new dataset. Please let me know if you have any questions. Thanks!  

[dat.bakdash2021.zip](https://github.com/wviechtb/metadat/files/7156350/dat.bakdash2021.zip)

**Comment by wviechtb** [comment]
Thanks for the submission! I or somebody else from the package author team will take a look at this eventually (I need to focus my attention elsewhere at the moment, but we will get to this).

**Comment by wviechtb** [comment]
I have now incorporated the dataset into the package. A few things with the data itself:

1. There were a few non-ASCII strings in the `Title` variable. Fixed.

2. Superfluous whitespace was removed from the `Author`, `Title`, and `DTIC.link` variables.

3. I removed the `Comments` variable from the exported dataset. If somebody wants to see the comments, they can always look at `dat.bakdash2021.csv` directly.

All changes were made in `dat.bakdash2021.r` so the original csv file is untouched.

There were also some issues with the example code:

1. Early on, you want to use cluster robust inference (`res.overall.crve`) but end up fitting the same model all over again and never use `robust()`. I fixed this. The comment states that `CRVE results are the same as the unadjusted results from res.overall to four decimal places`. Not entirely sure which part of the results this refers to, since the pooled estimate must be exactly identical. The SEs are indeed very similar (0.0240 versus 0.0239).

2. Loading the psych package just for `fisherz2r` is unnecessary when you have metafor loaded already and it provides `transf.ztor`. Strictly speaking, even that is superfluous, since this is identical to `tanh()`. I fixed this.

3. The way the CI for I^2 is computed isn't quite right. One cannot just take the lower and upper CI bounds for both variance components and construct a CI for I^2 that way. Instead, one can take the lower and upper CI bounds for the total amount of heterogeneity from the `res.overall.alt` model and use that for constructing a CI for I^2. I fixed this. Note that the CI for I^2 is therefore changed a bit compared to the one reported in the paper.

4. One cannot apply the z-to-r transformation to tau estimates. I removed the use of the transformation for the variance components. Since the values were relatively small, this leaves the rounded values almost unchanged.

5. Using `kable()` to create the table at the end isn't really necessary in the example code as this would only be relevant when creating some kind of (R)markdown document. Since this isn't happening anywhere, I removed the use of `kable()`.

6. Several small adjustments for consistency and clarity in the code and comments.

7. Removed `heterogeneity` as a concept term. It might be helpful to tag all datasets based on whether results are (mostly) heterogeneous or homogeneous, but then we would want to do this in some kind of consistent manner across all datasets.

You can see the docs for the dataset here: https://wviechtb.github.io/metadat/reference/dat.bakdash2021.html

If you disagree with any of the adjustments or would like to make further changes, let me know.
